package com.recoup.backend.model;

public enum CauseCategory {
    TRANSIENT_RETRYABLE,
    HARD_DECLINE_NEEDS_NEW_INSTRUMENT,
    CUSTOMER_ABANDONED,
    FRAUD_SUSPECTED,
    RECEIVABLE_GENTLE_STAGE,
    RECEIVABLE_ESCALATION_STAGE,
    RECEIVABLE_LEGAL_STAGE
}
